//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectsem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABULAR
    {
        public int Id { get; set; }
        public string FatherName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<short> Gender { get; set; }
        public string MotherName { get; set; }
        public string Email { get; set; }
        public string ResidentialAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<short> AdmissionFor { get; set; }
        public string EnrollmentNo { get; set; }
        public string Center { get; set; }
        public string Field { get; set; }
        public string Stream { get; set; }
        public string Sports { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string ClassObtained { get; set; }
        public string OutOf { get; set; }
        public string University { get; set; }
        public string MarksSecured { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual COURSE COURSE { get; set; }
    }
}
